[login]
[login.user1]
USERNAME = "PAI AUSENTE"
PASSWORD = "RAIAM"
ROLE = "ADMIN"

[database]
user = "sortenabet"
password = "*r7.,~V=l;]t<"jB9$4Q"
host = "sortenabetdb.postgres.database.azure.com"
port = "5432"
database = "sortenabet"